// Generated by DAL edge/IoT backend. For embedded, set CARGO_BUILD_TARGET (e.g. thumbv7em-none-eabihf).
#![allow(dead_code)]

pub mod edgegateway {
    pub struct State {
        pub device_count: i64,
        pub last_reading: f64,
    }
    /// Edge stub: replace with device logic or keep default.
    pub fn on_sensor_reading(sensor_id: String, value: f64) -> bool {
        false
    }
    /// Edge stub: replace with device logic or keep default.
    pub fn get_status() -> std::collections::HashMap<String, f64> {
        Default::default()
    }
}

